### ISSUE TITLE
NumOccupied for inversion symmetric systems with SOC

### ISSUE THREAD

**Issue by gmm05126** [quanshengwu/wannier_tools#36]
Dear QuanSheng,

For a system with inversion symmetry and SOC having occupied 3 doubly (spin) degenerated bands (6 electrons) what should I put for NumOccupied?

Band structure thumb here:
https://my.pcloud.com/publink/show?code=XZ6S8W7ZR6uDpRUgCIbBrbEPcyE1b0jKeIPy

Thanks,
Martin

p.s. I have checked BulkFS_calc = T for that quasi 2D system (slab). The FS3D.bxsf file contains constant eigenenergies for each band, which should not be like that, or? I am using WT v2.3.0

**Comment by quanshengwu** [comment]
Dear Martin, 

At present, FS3D.bxsf only contains 16 energy bands around to the NumOccupied band. For example. If Numoccupied = 10, then bands 3-18 will be written in the FS3D.bxsf. I did this because I don't want to put so many useless bands in this file. 

In you case, I would set NumOccupied = 6 if you show all the bands in your plot.  

QuanSheng
