### ISSUE TITLE
MLWF related topological properties

### ISSUE THREAD

**Issue by tron1989** [quanshengwu/wannier_tools#6]
Dear Quansheng Wu,

If the wannier functions are not fully maximum localized, does that affect the calculations of edge states and fermi arcs of topological materials?

For I have noticed that though the Wannier TB band structure fits well with DFT band structure, the not maximum localized WF will results in weird fermi arcs that seems not trustly.

And an examples indicate that, sometime we do not need to further wannierize (num_iter=0 in wannier90.win), is this the consideration of the "sysmetry-adapted" wannier functions?

Thanks in advance.

**Comment by quanshengwu** [comment]
Yes, It will affect. If you Wannier functions are very extended. Then this tight binding model is not good. It also means the transferability is not good. 

However, you don't have to do the fully maximum localize step as long as your orbitals is localize enough. For example, the spread of the Wannier function is smaller than one unit cell.  At this point, the transferability of the Wannier TB is good. Then the fermi arc will not change much.

If you set the coordinate system and the projectors properly, then even if you set num_iter=0, the Wannier functions will be local enough. num_iter=0 means your Wannier functions are very close to the original atomic orbitals. If you set num_iter with many steps, then Wannier90 will mix these atomic-orbital like WFs in order to get more localized WFs.

**Comment by tron1989** [comment]
Thanks for your rapid reply.

To get the suitable MLWFs, have you any suggestions on the initial projectors, the outer energy window and the inner frozen window (for example, the range of outer energy window should be how larger than the inner frozen window?) etc.

Maybe  I have to post this question on Wannier90 fortum instead of bothering you.

Also, I noticed that in the PRX paper on triple degenerate topological insulators (you as an coauthor), there is a post-processing  progress to symmetry the wannier TB bashed on the symmetry operations of the crystalline  materials, is it a specific task and could not be included in your codes?

**Comment by quanshengwu** [comment]
In order to get good WFs, first, you need to analyze the character of the bands. Pyprocar will help you if you use VASP. (https://sourceforge.net/p/pyprocar/PyPROCAR/HEAD/tree/). Then you choose the projectors according to the character around Fermi level. The outer window should include all the bands that have contribution to the projectors you choose. The inner window should exclude all other bands which has contribution in this window.

For the symmetrization part, that codes are written in python and not ready to publish.

**Comment by tron1989** [comment]
Yeah, indeed p4vasp can also do the orbit-projected band structure.

I noticed that the new version of input has an CARD as WANNIER_CENTRES, is it just related with the Wilson loop methods?

Thanks

**Comment by quanshengwu** [comment]
Yes, exactly. The WANNIER_CENTRES will affect the Wilson loop results. It is better to copy the WANNIER_CENTRES from wannier90.wout to input.dat.
